// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: community/apps/gramx/fifty/zero/ethos/mesh_demo/entities.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EAMV8002 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Eamvt8004     string                 `protobuf:"bytes,1,opt,name=eamvt8004,proto3" json:"eamvt8004,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EAMV8002) Reset() {
	*x = EAMV8002{}
	mi := &file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EAMV8002) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EAMV8002) ProtoMessage() {}

func (x *EAMV8002) ProtoReflect() protoreflect.Message {
	mi := &file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EAMV8002.ProtoReflect.Descriptor instead.
func (*EAMV8002) Descriptor() ([]byte, []int) {
	return file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_rawDescGZIP(), []int{0}
}

func (x *EAMV8002) GetEamvt8004() string {
	if x != nil {
		return x.Eamvt8004
	}
	return ""
}

type EAMV8001 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Eamvt8001     string                 `protobuf:"bytes,1,opt,name=eamvt8001,proto3" json:"eamvt8001,omitempty"`
	Eamvt8002     string                 `protobuf:"bytes,2,opt,name=eamvt8002,proto3" json:"eamvt8002,omitempty"`
	Eamvt8003     string                 `protobuf:"bytes,3,opt,name=eamvt8003,proto3" json:"eamvt8003,omitempty"`
	Eamvt8028     float64                `protobuf:"fixed64,4,opt,name=eamvt8028,proto3" json:"eamvt8028,omitempty"`
	Eamvt8029     float32                `protobuf:"fixed32,5,opt,name=eamvt8029,proto3" json:"eamvt8029,omitempty"`
	Eamvt8007     int64                  `protobuf:"varint,6,opt,name=eamvt8007,proto3" json:"eamvt8007,omitempty"`
	Eamvt8008     bool                   `protobuf:"varint,7,opt,name=eamvt8008,proto3" json:"eamvt8008,omitempty"`
	Eamvt8009     []byte                 `protobuf:"bytes,8,opt,name=eamvt8009,proto3" json:"eamvt8009,omitempty"`
	Eamvt8010     *EAMV8003              `protobuf:"bytes,9,opt,name=eamvt8010,proto3" json:"eamvt8010,omitempty"`
	Eamvt8011     int32                  `protobuf:"varint,10,opt,name=eamvt8011,proto3" json:"eamvt8011,omitempty"`
	Eamvt8012     uint32                 `protobuf:"varint,11,opt,name=eamvt8012,proto3" json:"eamvt8012,omitempty"`
	Eamvt8013     uint64                 `protobuf:"varint,12,opt,name=eamvt8013,proto3" json:"eamvt8013,omitempty"`
	Eamvt8014     int32                  `protobuf:"zigzag32,13,opt,name=eamvt8014,proto3" json:"eamvt8014,omitempty"`
	Eamvt8015     int64                  `protobuf:"zigzag64,14,opt,name=eamvt8015,proto3" json:"eamvt8015,omitempty"`
	Eamvt8016     uint32                 `protobuf:"fixed32,15,opt,name=eamvt8016,proto3" json:"eamvt8016,omitempty"`
	Eamvt8017     uint64                 `protobuf:"fixed64,16,opt,name=eamvt8017,proto3" json:"eamvt8017,omitempty"`
	Eamvt8018     int32                  `protobuf:"fixed32,17,opt,name=eamvt8018,proto3" json:"eamvt8018,omitempty"`
	Eamvt8019     int64                  `protobuf:"fixed64,18,opt,name=eamvt8019,proto3" json:"eamvt8019,omitempty"`
	Eamvt8020     *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=eamvt8020,proto3" json:"eamvt8020,omitempty"`
	Eamvt8021     *durationpb.Duration   `protobuf:"bytes,20,opt,name=eamvt8021,proto3" json:"eamvt8021,omitempty"`
	Eamvt8022     *emptypb.Empty         `protobuf:"bytes,21,opt,name=eamvt8022,proto3" json:"eamvt8022,omitempty"`
	Eamvt8023     *structpb.Struct       `protobuf:"bytes,22,opt,name=eamvt8023,proto3" json:"eamvt8023,omitempty"`
	Eamvt8024     *anypb.Any             `protobuf:"bytes,23,opt,name=eamvt8024,proto3" json:"eamvt8024,omitempty"`
	Eamvt8025     *fieldmaskpb.FieldMask `protobuf:"bytes,24,opt,name=eamvt8025,proto3" json:"eamvt8025,omitempty"`
	Eamvt8030     *structpb.ListValue    `protobuf:"bytes,25,opt,name=eamvt8030,proto3" json:"eamvt8030,omitempty"`
	Eamvt8031     *EAMV8002              `protobuf:"bytes,26,opt,name=eamvt8031,proto3" json:"eamvt8031,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EAMV8001) Reset() {
	*x = EAMV8001{}
	mi := &file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EAMV8001) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EAMV8001) ProtoMessage() {}

func (x *EAMV8001) ProtoReflect() protoreflect.Message {
	mi := &file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EAMV8001.ProtoReflect.Descriptor instead.
func (*EAMV8001) Descriptor() ([]byte, []int) {
	return file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_rawDescGZIP(), []int{1}
}

func (x *EAMV8001) GetEamvt8001() string {
	if x != nil {
		return x.Eamvt8001
	}
	return ""
}

func (x *EAMV8001) GetEamvt8002() string {
	if x != nil {
		return x.Eamvt8002
	}
	return ""
}

func (x *EAMV8001) GetEamvt8003() string {
	if x != nil {
		return x.Eamvt8003
	}
	return ""
}

func (x *EAMV8001) GetEamvt8028() float64 {
	if x != nil {
		return x.Eamvt8028
	}
	return 0
}

func (x *EAMV8001) GetEamvt8029() float32 {
	if x != nil {
		return x.Eamvt8029
	}
	return 0
}

func (x *EAMV8001) GetEamvt8007() int64 {
	if x != nil {
		return x.Eamvt8007
	}
	return 0
}

func (x *EAMV8001) GetEamvt8008() bool {
	if x != nil {
		return x.Eamvt8008
	}
	return false
}

func (x *EAMV8001) GetEamvt8009() []byte {
	if x != nil {
		return x.Eamvt8009
	}
	return nil
}

func (x *EAMV8001) GetEamvt8010() *EAMV8003 {
	if x != nil {
		return x.Eamvt8010
	}
	return nil
}

func (x *EAMV8001) GetEamvt8011() int32 {
	if x != nil {
		return x.Eamvt8011
	}
	return 0
}

func (x *EAMV8001) GetEamvt8012() uint32 {
	if x != nil {
		return x.Eamvt8012
	}
	return 0
}

func (x *EAMV8001) GetEamvt8013() uint64 {
	if x != nil {
		return x.Eamvt8013
	}
	return 0
}

func (x *EAMV8001) GetEamvt8014() int32 {
	if x != nil {
		return x.Eamvt8014
	}
	return 0
}

func (x *EAMV8001) GetEamvt8015() int64 {
	if x != nil {
		return x.Eamvt8015
	}
	return 0
}

func (x *EAMV8001) GetEamvt8016() uint32 {
	if x != nil {
		return x.Eamvt8016
	}
	return 0
}

func (x *EAMV8001) GetEamvt8017() uint64 {
	if x != nil {
		return x.Eamvt8017
	}
	return 0
}

func (x *EAMV8001) GetEamvt8018() int32 {
	if x != nil {
		return x.Eamvt8018
	}
	return 0
}

func (x *EAMV8001) GetEamvt8019() int64 {
	if x != nil {
		return x.Eamvt8019
	}
	return 0
}

func (x *EAMV8001) GetEamvt8020() *timestamppb.Timestamp {
	if x != nil {
		return x.Eamvt8020
	}
	return nil
}

func (x *EAMV8001) GetEamvt8021() *durationpb.Duration {
	if x != nil {
		return x.Eamvt8021
	}
	return nil
}

func (x *EAMV8001) GetEamvt8022() *emptypb.Empty {
	if x != nil {
		return x.Eamvt8022
	}
	return nil
}

func (x *EAMV8001) GetEamvt8023() *structpb.Struct {
	if x != nil {
		return x.Eamvt8023
	}
	return nil
}

func (x *EAMV8001) GetEamvt8024() *anypb.Any {
	if x != nil {
		return x.Eamvt8024
	}
	return nil
}

func (x *EAMV8001) GetEamvt8025() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Eamvt8025
	}
	return nil
}

func (x *EAMV8001) GetEamvt8030() *structpb.ListValue {
	if x != nil {
		return x.Eamvt8030
	}
	return nil
}

func (x *EAMV8001) GetEamvt8031() *EAMV8002 {
	if x != nil {
		return x.Eamvt8031
	}
	return nil
}

type EAMV8003 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Eamvt8005     string                 `protobuf:"bytes,1,opt,name=eamvt8005,proto3" json:"eamvt8005,omitempty"`
	Eamvt8032     float64                `protobuf:"fixed64,2,opt,name=eamvt8032,proto3" json:"eamvt8032,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EAMV8003) Reset() {
	*x = EAMV8003{}
	mi := &file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EAMV8003) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EAMV8003) ProtoMessage() {}

func (x *EAMV8003) ProtoReflect() protoreflect.Message {
	mi := &file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EAMV8003.ProtoReflect.Descriptor instead.
func (*EAMV8003) Descriptor() ([]byte, []int) {
	return file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_rawDescGZIP(), []int{2}
}

func (x *EAMV8003) GetEamvt8005() string {
	if x != nil {
		return x.Eamvt8005
	}
	return ""
}

func (x *EAMV8003) GetEamvt8032() float64 {
	if x != nil {
		return x.Eamvt8032
	}
	return 0
}

type EAMV8004 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Eamvt8033     string                 `protobuf:"bytes,1,opt,name=eamvt8033,proto3" json:"eamvt8033,omitempty"`
	Eamvt8034     bool                   `protobuf:"varint,2,opt,name=eamvt8034,proto3" json:"eamvt8034,omitempty"`
	Eamvt8035     int32                  `protobuf:"varint,3,opt,name=eamvt8035,proto3" json:"eamvt8035,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EAMV8004) Reset() {
	*x = EAMV8004{}
	mi := &file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EAMV8004) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EAMV8004) ProtoMessage() {}

func (x *EAMV8004) ProtoReflect() protoreflect.Message {
	mi := &file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EAMV8004.ProtoReflect.Descriptor instead.
func (*EAMV8004) Descriptor() ([]byte, []int) {
	return file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_rawDescGZIP(), []int{3}
}

func (x *EAMV8004) GetEamvt8033() string {
	if x != nil {
		return x.Eamvt8033
	}
	return ""
}

func (x *EAMV8004) GetEamvt8034() bool {
	if x != nil {
		return x.Eamvt8034
	}
	return false
}

func (x *EAMV8004) GetEamvt8035() int32 {
	if x != nil {
		return x.Eamvt8035
	}
	return 0
}

var File_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto protoreflect.FileDescriptor

const file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_rawDesc = "" +
	"\n" +
	">community/apps/gramx/fifty/zero/ethos/mesh_demo/entities.proto\x12/community.apps.gramx.fifty.zero.ethos.mesh_demo\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x19google/protobuf/any.proto\x1a google/protobuf/field_mask.proto\"(\n" +
	"\bEAMV8002\x12\x1c\n" +
	"\teamvt8004\x18\x01 \x01(\tR\teamvt8004\"\xc2\b\n" +
	"\bEAMV8001\x12\x1c\n" +
	"\teamvt8001\x18\x01 \x01(\tR\teamvt8001\x12\x1c\n" +
	"\teamvt8002\x18\x02 \x01(\tR\teamvt8002\x12\x1c\n" +
	"\teamvt8003\x18\x03 \x01(\tR\teamvt8003\x12\x1c\n" +
	"\teamvt8028\x18\x04 \x01(\x01R\teamvt8028\x12\x1c\n" +
	"\teamvt8029\x18\x05 \x01(\x02R\teamvt8029\x12\x1c\n" +
	"\teamvt8007\x18\x06 \x01(\x03R\teamvt8007\x12\x1c\n" +
	"\teamvt8008\x18\a \x01(\bR\teamvt8008\x12\x1c\n" +
	"\teamvt8009\x18\b \x01(\fR\teamvt8009\x12W\n" +
	"\teamvt8010\x18\t \x01(\v29.community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8003R\teamvt8010\x12\x1c\n" +
	"\teamvt8011\x18\n" +
	" \x01(\x05R\teamvt8011\x12\x1c\n" +
	"\teamvt8012\x18\v \x01(\rR\teamvt8012\x12\x1c\n" +
	"\teamvt8013\x18\f \x01(\x04R\teamvt8013\x12\x1c\n" +
	"\teamvt8014\x18\r \x01(\x11R\teamvt8014\x12\x1c\n" +
	"\teamvt8015\x18\x0e \x01(\x12R\teamvt8015\x12\x1c\n" +
	"\teamvt8016\x18\x0f \x01(\aR\teamvt8016\x12\x1c\n" +
	"\teamvt8017\x18\x10 \x01(\x06R\teamvt8017\x12\x1c\n" +
	"\teamvt8018\x18\x11 \x01(\x0fR\teamvt8018\x12\x1c\n" +
	"\teamvt8019\x18\x12 \x01(\x10R\teamvt8019\x128\n" +
	"\teamvt8020\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\teamvt8020\x127\n" +
	"\teamvt8021\x18\x14 \x01(\v2\x19.google.protobuf.DurationR\teamvt8021\x124\n" +
	"\teamvt8022\x18\x15 \x01(\v2\x16.google.protobuf.EmptyR\teamvt8022\x125\n" +
	"\teamvt8023\x18\x16 \x01(\v2\x17.google.protobuf.StructR\teamvt8023\x122\n" +
	"\teamvt8024\x18\x17 \x01(\v2\x14.google.protobuf.AnyR\teamvt8024\x128\n" +
	"\teamvt8025\x18\x18 \x01(\v2\x1a.google.protobuf.FieldMaskR\teamvt8025\x128\n" +
	"\teamvt8030\x18\x19 \x01(\v2\x1a.google.protobuf.ListValueR\teamvt8030\x12W\n" +
	"\teamvt8031\x18\x1a \x01(\v29.community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8002R\teamvt8031\"F\n" +
	"\bEAMV8003\x12\x1c\n" +
	"\teamvt8005\x18\x01 \x01(\tR\teamvt8005\x12\x1c\n" +
	"\teamvt8032\x18\x02 \x01(\x01R\teamvt8032\"d\n" +
	"\bEAMV8004\x12\x1c\n" +
	"\teamvt8033\x18\x01 \x01(\tR\teamvt8033\x12\x1c\n" +
	"\teamvt8034\x18\x02 \x01(\bR\teamvt8034\x12\x1c\n" +
	"\teamvt8035\x18\x03 \x01(\x05R\teamvt8035BiZggithub.com/50gramx/eapp-golang-domain/community/apps/gramx/fifty/zero/ethos/mesh_demo/entities;entitiesb\x06proto3"

var (
	file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_rawDescOnce sync.Once
	file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_rawDescData []byte
)

func file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_rawDescGZIP() []byte {
	file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_rawDescOnce.Do(func() {
		file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_rawDesc), len(file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_rawDesc)))
	})
	return file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_rawDescData
}

var file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_goTypes = []any{
	(*EAMV8002)(nil),              // 0: community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8002
	(*EAMV8001)(nil),              // 1: community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001
	(*EAMV8003)(nil),              // 2: community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8003
	(*EAMV8004)(nil),              // 3: community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8004
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 5: google.protobuf.Duration
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
	(*structpb.Struct)(nil),       // 7: google.protobuf.Struct
	(*anypb.Any)(nil),             // 8: google.protobuf.Any
	(*fieldmaskpb.FieldMask)(nil), // 9: google.protobuf.FieldMask
	(*structpb.ListValue)(nil),    // 10: google.protobuf.ListValue
}
var file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_depIdxs = []int32{
	2,  // 0: community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001.eamvt8010:type_name -> community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8003
	4,  // 1: community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001.eamvt8020:type_name -> google.protobuf.Timestamp
	5,  // 2: community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001.eamvt8021:type_name -> google.protobuf.Duration
	6,  // 3: community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001.eamvt8022:type_name -> google.protobuf.Empty
	7,  // 4: community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001.eamvt8023:type_name -> google.protobuf.Struct
	8,  // 5: community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001.eamvt8024:type_name -> google.protobuf.Any
	9,  // 6: community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001.eamvt8025:type_name -> google.protobuf.FieldMask
	10, // 7: community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001.eamvt8030:type_name -> google.protobuf.ListValue
	0,  // 8: community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001.eamvt8031:type_name -> community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8002
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_init() }
func file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_init() {
	if File_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_rawDesc), len(file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_goTypes,
		DependencyIndexes: file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_depIdxs,
		MessageInfos:      file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_msgTypes,
	}.Build()
	File_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto = out.File
	file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_goTypes = nil
	file_community_apps_gramx_fifty_zero_ethos_mesh_demo_entities_proto_depIdxs = nil
}
