// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: community/apps/gramx/fifty/zero/epn/epn_peers/entities.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EAMV7100 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Eamvt7100     string                 `protobuf:"bytes,1,opt,name=eamvt7100,proto3" json:"eamvt7100,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EAMV7100) Reset() {
	*x = EAMV7100{}
	mi := &file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EAMV7100) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EAMV7100) ProtoMessage() {}

func (x *EAMV7100) ProtoReflect() protoreflect.Message {
	mi := &file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EAMV7100.ProtoReflect.Descriptor instead.
func (*EAMV7100) Descriptor() ([]byte, []int) {
	return file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_rawDescGZIP(), []int{0}
}

func (x *EAMV7100) GetEamvt7100() string {
	if x != nil {
		return x.Eamvt7100
	}
	return ""
}

type EAMV7101 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Eamvt7101     string                 `protobuf:"bytes,1,opt,name=eamvt7101,proto3" json:"eamvt7101,omitempty"`
	Eamvt7102     string                 `protobuf:"bytes,2,opt,name=eamvt7102,proto3" json:"eamvt7102,omitempty"`
	Eamvt7103     []string               `protobuf:"bytes,3,rep,name=eamvt7103,proto3" json:"eamvt7103,omitempty"`
	Eamvt7104     string                 `protobuf:"bytes,4,opt,name=eamvt7104,proto3" json:"eamvt7104,omitempty"`
	Eamvt7105     bool                   `protobuf:"varint,5,opt,name=eamvt7105,proto3" json:"eamvt7105,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EAMV7101) Reset() {
	*x = EAMV7101{}
	mi := &file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EAMV7101) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EAMV7101) ProtoMessage() {}

func (x *EAMV7101) ProtoReflect() protoreflect.Message {
	mi := &file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EAMV7101.ProtoReflect.Descriptor instead.
func (*EAMV7101) Descriptor() ([]byte, []int) {
	return file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_rawDescGZIP(), []int{1}
}

func (x *EAMV7101) GetEamvt7101() string {
	if x != nil {
		return x.Eamvt7101
	}
	return ""
}

func (x *EAMV7101) GetEamvt7102() string {
	if x != nil {
		return x.Eamvt7102
	}
	return ""
}

func (x *EAMV7101) GetEamvt7103() []string {
	if x != nil {
		return x.Eamvt7103
	}
	return nil
}

func (x *EAMV7101) GetEamvt7104() string {
	if x != nil {
		return x.Eamvt7104
	}
	return ""
}

func (x *EAMV7101) GetEamvt7105() bool {
	if x != nil {
		return x.Eamvt7105
	}
	return false
}

type EAMV7103 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Eamvt7111     []*EAMV7102            `protobuf:"bytes,1,rep,name=eamvt7111,proto3" json:"eamvt7111,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EAMV7103) Reset() {
	*x = EAMV7103{}
	mi := &file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EAMV7103) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EAMV7103) ProtoMessage() {}

func (x *EAMV7103) ProtoReflect() protoreflect.Message {
	mi := &file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EAMV7103.ProtoReflect.Descriptor instead.
func (*EAMV7103) Descriptor() ([]byte, []int) {
	return file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_rawDescGZIP(), []int{2}
}

func (x *EAMV7103) GetEamvt7111() []*EAMV7102 {
	if x != nil {
		return x.Eamvt7111
	}
	return nil
}

type EAMV7102 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Eamvt7106     string                 `protobuf:"bytes,1,opt,name=eamvt7106,proto3" json:"eamvt7106,omitempty"`
	Eamvt7107     string                 `protobuf:"bytes,2,opt,name=eamvt7107,proto3" json:"eamvt7107,omitempty"`
	Eamvt7108     []string               `protobuf:"bytes,3,rep,name=eamvt7108,proto3" json:"eamvt7108,omitempty"`
	Eamvt7109     []string               `protobuf:"bytes,4,rep,name=eamvt7109,proto3" json:"eamvt7109,omitempty"`
	Eamvt7110     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=eamvt7110,proto3" json:"eamvt7110,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EAMV7102) Reset() {
	*x = EAMV7102{}
	mi := &file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EAMV7102) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EAMV7102) ProtoMessage() {}

func (x *EAMV7102) ProtoReflect() protoreflect.Message {
	mi := &file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EAMV7102.ProtoReflect.Descriptor instead.
func (*EAMV7102) Descriptor() ([]byte, []int) {
	return file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_rawDescGZIP(), []int{3}
}

func (x *EAMV7102) GetEamvt7106() string {
	if x != nil {
		return x.Eamvt7106
	}
	return ""
}

func (x *EAMV7102) GetEamvt7107() string {
	if x != nil {
		return x.Eamvt7107
	}
	return ""
}

func (x *EAMV7102) GetEamvt7108() []string {
	if x != nil {
		return x.Eamvt7108
	}
	return nil
}

func (x *EAMV7102) GetEamvt7109() []string {
	if x != nil {
		return x.Eamvt7109
	}
	return nil
}

func (x *EAMV7102) GetEamvt7110() *timestamppb.Timestamp {
	if x != nil {
		return x.Eamvt7110
	}
	return nil
}

type EAMV7104 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Eamvt7112     string                 `protobuf:"bytes,1,opt,name=eamvt7112,proto3" json:"eamvt7112,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EAMV7104) Reset() {
	*x = EAMV7104{}
	mi := &file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EAMV7104) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EAMV7104) ProtoMessage() {}

func (x *EAMV7104) ProtoReflect() protoreflect.Message {
	mi := &file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EAMV7104.ProtoReflect.Descriptor instead.
func (*EAMV7104) Descriptor() ([]byte, []int) {
	return file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_rawDescGZIP(), []int{4}
}

func (x *EAMV7104) GetEamvt7112() string {
	if x != nil {
		return x.Eamvt7112
	}
	return ""
}

type EAMV7105 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Eamvt7113     string                 `protobuf:"bytes,1,opt,name=eamvt7113,proto3" json:"eamvt7113,omitempty"`
	Eamvt7114     string                 `protobuf:"bytes,2,opt,name=eamvt7114,proto3" json:"eamvt7114,omitempty"`
	Eamvt7115     bool                   `protobuf:"varint,3,opt,name=eamvt7115,proto3" json:"eamvt7115,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EAMV7105) Reset() {
	*x = EAMV7105{}
	mi := &file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EAMV7105) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EAMV7105) ProtoMessage() {}

func (x *EAMV7105) ProtoReflect() protoreflect.Message {
	mi := &file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EAMV7105.ProtoReflect.Descriptor instead.
func (*EAMV7105) Descriptor() ([]byte, []int) {
	return file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_rawDescGZIP(), []int{5}
}

func (x *EAMV7105) GetEamvt7113() string {
	if x != nil {
		return x.Eamvt7113
	}
	return ""
}

func (x *EAMV7105) GetEamvt7114() string {
	if x != nil {
		return x.Eamvt7114
	}
	return ""
}

func (x *EAMV7105) GetEamvt7115() bool {
	if x != nil {
		return x.Eamvt7115
	}
	return false
}

type EAMV7106 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Eamvt7116     string                 `protobuf:"bytes,1,opt,name=eamvt7116,proto3" json:"eamvt7116,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EAMV7106) Reset() {
	*x = EAMV7106{}
	mi := &file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EAMV7106) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EAMV7106) ProtoMessage() {}

func (x *EAMV7106) ProtoReflect() protoreflect.Message {
	mi := &file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EAMV7106.ProtoReflect.Descriptor instead.
func (*EAMV7106) Descriptor() ([]byte, []int) {
	return file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_rawDescGZIP(), []int{6}
}

func (x *EAMV7106) GetEamvt7116() string {
	if x != nil {
		return x.Eamvt7116
	}
	return ""
}

type EAMV7107 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Eamvt7117     string                 `protobuf:"bytes,1,opt,name=eamvt7117,proto3" json:"eamvt7117,omitempty"`
	Eamvt7118     string                 `protobuf:"bytes,2,opt,name=eamvt7118,proto3" json:"eamvt7118,omitempty"`
	Eamvt7119     string                 `protobuf:"bytes,3,opt,name=eamvt7119,proto3" json:"eamvt7119,omitempty"`
	Eamvt7120     string                 `protobuf:"bytes,4,opt,name=eamvt7120,proto3" json:"eamvt7120,omitempty"`
	Eamvt7121     string                 `protobuf:"bytes,5,opt,name=eamvt7121,proto3" json:"eamvt7121,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EAMV7107) Reset() {
	*x = EAMV7107{}
	mi := &file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EAMV7107) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EAMV7107) ProtoMessage() {}

func (x *EAMV7107) ProtoReflect() protoreflect.Message {
	mi := &file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EAMV7107.ProtoReflect.Descriptor instead.
func (*EAMV7107) Descriptor() ([]byte, []int) {
	return file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_rawDescGZIP(), []int{7}
}

func (x *EAMV7107) GetEamvt7117() string {
	if x != nil {
		return x.Eamvt7117
	}
	return ""
}

func (x *EAMV7107) GetEamvt7118() string {
	if x != nil {
		return x.Eamvt7118
	}
	return ""
}

func (x *EAMV7107) GetEamvt7119() string {
	if x != nil {
		return x.Eamvt7119
	}
	return ""
}

func (x *EAMV7107) GetEamvt7120() string {
	if x != nil {
		return x.Eamvt7120
	}
	return ""
}

func (x *EAMV7107) GetEamvt7121() string {
	if x != nil {
		return x.Eamvt7121
	}
	return ""
}

var File_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto protoreflect.FileDescriptor

const file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_rawDesc = "" +
	"\n" +
	"<community/apps/gramx/fifty/zero/epn/epn_peers/entities.proto\x12-community.apps.gramx.fifty.zero.epn.epn_peers\x1a\x1fgoogle/protobuf/timestamp.proto\"(\n" +
	"\bEAMV7100\x12\x1c\n" +
	"\teamvt7100\x18\x01 \x01(\tR\teamvt7100\"\xa0\x01\n" +
	"\bEAMV7101\x12\x1c\n" +
	"\teamvt7101\x18\x01 \x01(\tR\teamvt7101\x12\x1c\n" +
	"\teamvt7102\x18\x02 \x01(\tR\teamvt7102\x12\x1c\n" +
	"\teamvt7103\x18\x03 \x03(\tR\teamvt7103\x12\x1c\n" +
	"\teamvt7104\x18\x04 \x01(\tR\teamvt7104\x12\x1c\n" +
	"\teamvt7105\x18\x05 \x01(\bR\teamvt7105\"a\n" +
	"\bEAMV7103\x12U\n" +
	"\teamvt7111\x18\x01 \x03(\v27.community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7102R\teamvt7111\"\xbc\x01\n" +
	"\bEAMV7102\x12\x1c\n" +
	"\teamvt7106\x18\x01 \x01(\tR\teamvt7106\x12\x1c\n" +
	"\teamvt7107\x18\x02 \x01(\tR\teamvt7107\x12\x1c\n" +
	"\teamvt7108\x18\x03 \x03(\tR\teamvt7108\x12\x1c\n" +
	"\teamvt7109\x18\x04 \x03(\tR\teamvt7109\x128\n" +
	"\teamvt7110\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\teamvt7110\"(\n" +
	"\bEAMV7104\x12\x1c\n" +
	"\teamvt7112\x18\x01 \x01(\tR\teamvt7112\"d\n" +
	"\bEAMV7105\x12\x1c\n" +
	"\teamvt7113\x18\x01 \x01(\tR\teamvt7113\x12\x1c\n" +
	"\teamvt7114\x18\x02 \x01(\tR\teamvt7114\x12\x1c\n" +
	"\teamvt7115\x18\x03 \x01(\bR\teamvt7115\"(\n" +
	"\bEAMV7106\x12\x1c\n" +
	"\teamvt7116\x18\x01 \x01(\tR\teamvt7116\"\xa0\x01\n" +
	"\bEAMV7107\x12\x1c\n" +
	"\teamvt7117\x18\x01 \x01(\tR\teamvt7117\x12\x1c\n" +
	"\teamvt7118\x18\x02 \x01(\tR\teamvt7118\x12\x1c\n" +
	"\teamvt7119\x18\x03 \x01(\tR\teamvt7119\x12\x1c\n" +
	"\teamvt7120\x18\x04 \x01(\tR\teamvt7120\x12\x1c\n" +
	"\teamvt7121\x18\x05 \x01(\tR\teamvt7121BgZegithub.com/50gramx/eapp-golang-domain/community/apps/gramx/fifty/zero/epn/epn_peers/entities;entitiesb\x06proto3"

var (
	file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_rawDescOnce sync.Once
	file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_rawDescData []byte
)

func file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_rawDescGZIP() []byte {
	file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_rawDescOnce.Do(func() {
		file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_rawDesc), len(file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_rawDesc)))
	})
	return file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_rawDescData
}

var file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_goTypes = []any{
	(*EAMV7100)(nil),              // 0: community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7100
	(*EAMV7101)(nil),              // 1: community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7101
	(*EAMV7103)(nil),              // 2: community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7103
	(*EAMV7102)(nil),              // 3: community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7102
	(*EAMV7104)(nil),              // 4: community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7104
	(*EAMV7105)(nil),              // 5: community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7105
	(*EAMV7106)(nil),              // 6: community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7106
	(*EAMV7107)(nil),              // 7: community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7107
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_depIdxs = []int32{
	3, // 0: community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7103.eamvt7111:type_name -> community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7102
	8, // 1: community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7102.eamvt7110:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_init() }
func file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_init() {
	if File_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_rawDesc), len(file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_goTypes,
		DependencyIndexes: file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_depIdxs,
		MessageInfos:      file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_msgTypes,
	}.Build()
	File_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto = out.File
	file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_goTypes = nil
	file_community_apps_gramx_fifty_zero_epn_epn_peers_entities_proto_depIdxs = nil
}
