// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: community/apps/gramx/fifty/zero/epn/epn_agent_chat/entities.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EAMV6001 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Eamvt6001     string                 `protobuf:"bytes,1,opt,name=eamvt6001,proto3" json:"eamvt6001,omitempty"`
	Eamvt6002     string                 `protobuf:"bytes,2,opt,name=eamvt6002,proto3" json:"eamvt6002,omitempty"`
	Eamvt6003     string                 `protobuf:"bytes,3,opt,name=eamvt6003,proto3" json:"eamvt6003,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EAMV6001) Reset() {
	*x = EAMV6001{}
	mi := &file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EAMV6001) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EAMV6001) ProtoMessage() {}

func (x *EAMV6001) ProtoReflect() protoreflect.Message {
	mi := &file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EAMV6001.ProtoReflect.Descriptor instead.
func (*EAMV6001) Descriptor() ([]byte, []int) {
	return file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto_rawDescGZIP(), []int{0}
}

func (x *EAMV6001) GetEamvt6001() string {
	if x != nil {
		return x.Eamvt6001
	}
	return ""
}

func (x *EAMV6001) GetEamvt6002() string {
	if x != nil {
		return x.Eamvt6002
	}
	return ""
}

func (x *EAMV6001) GetEamvt6003() string {
	if x != nil {
		return x.Eamvt6003
	}
	return ""
}

type EAMV6002 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Eamvt6004     string                 `protobuf:"bytes,1,opt,name=eamvt6004,proto3" json:"eamvt6004,omitempty"`
	Eamvt6008     string                 `protobuf:"bytes,2,opt,name=eamvt6008,proto3" json:"eamvt6008,omitempty"`
	Eamvt6009     bool                   `protobuf:"varint,3,opt,name=eamvt6009,proto3" json:"eamvt6009,omitempty"`
	Eamvt6010     string                 `protobuf:"bytes,4,opt,name=eamvt6010,proto3" json:"eamvt6010,omitempty"`
	Eamvt6011     string                 `protobuf:"bytes,5,opt,name=eamvt6011,proto3" json:"eamvt6011,omitempty"`
	Eamvt6012     string                 `protobuf:"bytes,6,opt,name=eamvt6012,proto3" json:"eamvt6012,omitempty"`
	Eamvt6013     *structpb.ListValue    `protobuf:"bytes,7,opt,name=eamvt6013,proto3" json:"eamvt6013,omitempty"`
	Eamvt6014     *structpb.ListValue    `protobuf:"bytes,8,opt,name=eamvt6014,proto3" json:"eamvt6014,omitempty"`
	Eamvt6015     *structpb.ListValue    `protobuf:"bytes,9,opt,name=eamvt6015,proto3" json:"eamvt6015,omitempty"`
	Eamvt6016     string                 `protobuf:"bytes,10,opt,name=eamvt6016,proto3" json:"eamvt6016,omitempty"`
	Eamvt6017     string                 `protobuf:"bytes,11,opt,name=eamvt6017,proto3" json:"eamvt6017,omitempty"`
	Eamvt6018     string                 `protobuf:"bytes,12,opt,name=eamvt6018,proto3" json:"eamvt6018,omitempty"`
	Eamvt6019     string                 `protobuf:"bytes,13,opt,name=eamvt6019,proto3" json:"eamvt6019,omitempty"`
	Eamvt6020     string                 `protobuf:"bytes,14,opt,name=eamvt6020,proto3" json:"eamvt6020,omitempty"`
	Eamvt6021     string                 `protobuf:"bytes,15,opt,name=eamvt6021,proto3" json:"eamvt6021,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EAMV6002) Reset() {
	*x = EAMV6002{}
	mi := &file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EAMV6002) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EAMV6002) ProtoMessage() {}

func (x *EAMV6002) ProtoReflect() protoreflect.Message {
	mi := &file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EAMV6002.ProtoReflect.Descriptor instead.
func (*EAMV6002) Descriptor() ([]byte, []int) {
	return file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto_rawDescGZIP(), []int{1}
}

func (x *EAMV6002) GetEamvt6004() string {
	if x != nil {
		return x.Eamvt6004
	}
	return ""
}

func (x *EAMV6002) GetEamvt6008() string {
	if x != nil {
		return x.Eamvt6008
	}
	return ""
}

func (x *EAMV6002) GetEamvt6009() bool {
	if x != nil {
		return x.Eamvt6009
	}
	return false
}

func (x *EAMV6002) GetEamvt6010() string {
	if x != nil {
		return x.Eamvt6010
	}
	return ""
}

func (x *EAMV6002) GetEamvt6011() string {
	if x != nil {
		return x.Eamvt6011
	}
	return ""
}

func (x *EAMV6002) GetEamvt6012() string {
	if x != nil {
		return x.Eamvt6012
	}
	return ""
}

func (x *EAMV6002) GetEamvt6013() *structpb.ListValue {
	if x != nil {
		return x.Eamvt6013
	}
	return nil
}

func (x *EAMV6002) GetEamvt6014() *structpb.ListValue {
	if x != nil {
		return x.Eamvt6014
	}
	return nil
}

func (x *EAMV6002) GetEamvt6015() *structpb.ListValue {
	if x != nil {
		return x.Eamvt6015
	}
	return nil
}

func (x *EAMV6002) GetEamvt6016() string {
	if x != nil {
		return x.Eamvt6016
	}
	return ""
}

func (x *EAMV6002) GetEamvt6017() string {
	if x != nil {
		return x.Eamvt6017
	}
	return ""
}

func (x *EAMV6002) GetEamvt6018() string {
	if x != nil {
		return x.Eamvt6018
	}
	return ""
}

func (x *EAMV6002) GetEamvt6019() string {
	if x != nil {
		return x.Eamvt6019
	}
	return ""
}

func (x *EAMV6002) GetEamvt6020() string {
	if x != nil {
		return x.Eamvt6020
	}
	return ""
}

func (x *EAMV6002) GetEamvt6021() string {
	if x != nil {
		return x.Eamvt6021
	}
	return ""
}

var File_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto protoreflect.FileDescriptor

const file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto_rawDesc = "" +
	"\n" +
	"Acommunity/apps/gramx/fifty/zero/epn/epn_agent_chat/entities.proto\x122community.apps.gramx.fifty.zero.epn.epn_agent_chat\x1a\x1cgoogle/protobuf/struct.proto\"d\n" +
	"\bEAMV6001\x12\x1c\n" +
	"\teamvt6001\x18\x01 \x01(\tR\teamvt6001\x12\x1c\n" +
	"\teamvt6002\x18\x02 \x01(\tR\teamvt6002\x12\x1c\n" +
	"\teamvt6003\x18\x03 \x01(\tR\teamvt6003\"\xa0\x04\n" +
	"\bEAMV6002\x12\x1c\n" +
	"\teamvt6004\x18\x01 \x01(\tR\teamvt6004\x12\x1c\n" +
	"\teamvt6008\x18\x02 \x01(\tR\teamvt6008\x12\x1c\n" +
	"\teamvt6009\x18\x03 \x01(\bR\teamvt6009\x12\x1c\n" +
	"\teamvt6010\x18\x04 \x01(\tR\teamvt6010\x12\x1c\n" +
	"\teamvt6011\x18\x05 \x01(\tR\teamvt6011\x12\x1c\n" +
	"\teamvt6012\x18\x06 \x01(\tR\teamvt6012\x128\n" +
	"\teamvt6013\x18\a \x01(\v2\x1a.google.protobuf.ListValueR\teamvt6013\x128\n" +
	"\teamvt6014\x18\b \x01(\v2\x1a.google.protobuf.ListValueR\teamvt6014\x128\n" +
	"\teamvt6015\x18\t \x01(\v2\x1a.google.protobuf.ListValueR\teamvt6015\x12\x1c\n" +
	"\teamvt6016\x18\n" +
	" \x01(\tR\teamvt6016\x12\x1c\n" +
	"\teamvt6017\x18\v \x01(\tR\teamvt6017\x12\x1c\n" +
	"\teamvt6018\x18\f \x01(\tR\teamvt6018\x12\x1c\n" +
	"\teamvt6019\x18\r \x01(\tR\teamvt6019\x12\x1c\n" +
	"\teamvt6020\x18\x0e \x01(\tR\teamvt6020\x12\x1c\n" +
	"\teamvt6021\x18\x0f \x01(\tR\teamvt6021BlZjgithub.com/50gramx/eapp-golang-domain/community/apps/gramx/fifty/zero/epn/epn_agent_chat/entities;entitiesb\x06proto3"

var (
	file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto_rawDescOnce sync.Once
	file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto_rawDescData []byte
)

func file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto_rawDescGZIP() []byte {
	file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto_rawDescOnce.Do(func() {
		file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto_rawDesc), len(file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto_rawDesc)))
	})
	return file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto_rawDescData
}

var file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto_goTypes = []any{
	(*EAMV6001)(nil),           // 0: community.apps.gramx.fifty.zero.epn.epn_agent_chat.EAMV6001
	(*EAMV6002)(nil),           // 1: community.apps.gramx.fifty.zero.epn.epn_agent_chat.EAMV6002
	(*structpb.ListValue)(nil), // 2: google.protobuf.ListValue
}
var file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto_depIdxs = []int32{
	2, // 0: community.apps.gramx.fifty.zero.epn.epn_agent_chat.EAMV6002.eamvt6013:type_name -> google.protobuf.ListValue
	2, // 1: community.apps.gramx.fifty.zero.epn.epn_agent_chat.EAMV6002.eamvt6014:type_name -> google.protobuf.ListValue
	2, // 2: community.apps.gramx.fifty.zero.epn.epn_agent_chat.EAMV6002.eamvt6015:type_name -> google.protobuf.ListValue
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto_init() }
func file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto_init() {
	if File_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto_rawDesc), len(file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto_goTypes,
		DependencyIndexes: file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto_depIdxs,
		MessageInfos:      file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto_msgTypes,
	}.Build()
	File_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto = out.File
	file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto_goTypes = nil
	file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_entities_proto_depIdxs = nil
}
