// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: community/apps/gramx/fifty/zero/epn/epn_peers/EAMV7107_service.proto

package services

import (
	entities "github.com/50gramx/eapp-golang-domain/community/apps/gramx/fifty/zero/epn/epn_peers/entities"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_community_apps_gramx_fifty_zero_epn_epn_peers_EAMV7107_service_proto protoreflect.FileDescriptor

const file_community_apps_gramx_fifty_zero_epn_epn_peers_EAMV7107_service_proto_rawDesc = "" +
	"\n" +
	"Dcommunity/apps/gramx/fifty/zero/epn/epn_peers/EAMV7107_service.proto\x12-community.apps.gramx.fifty.zero.epn.epn_peers\x1a<community/apps/gramx/fifty/zero/epn/epn_peers/entities.proto2\x99\x01\n" +
	"\x17EAMV7107DiscoverService\x12~\n" +
	"\bEAMC7104\x127.community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7106\x1a7.community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7107(\x01BgZegithub.com/50gramx/eapp-golang-domain/community/apps/gramx/fifty/zero/epn/epn_peers/services;servicesb\x06proto3"

var file_community_apps_gramx_fifty_zero_epn_epn_peers_EAMV7107_service_proto_goTypes = []any{
	(*entities.EAMV7106)(nil), // 0: community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7106
	(*entities.EAMV7107)(nil), // 1: community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7107
}
var file_community_apps_gramx_fifty_zero_epn_epn_peers_EAMV7107_service_proto_depIdxs = []int32{
	0, // 0: community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7107DiscoverService.EAMC7104:input_type -> community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7106
	1, // 1: community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7107DiscoverService.EAMC7104:output_type -> community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7107
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_community_apps_gramx_fifty_zero_epn_epn_peers_EAMV7107_service_proto_init() }
func file_community_apps_gramx_fifty_zero_epn_epn_peers_EAMV7107_service_proto_init() {
	if File_community_apps_gramx_fifty_zero_epn_epn_peers_EAMV7107_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_community_apps_gramx_fifty_zero_epn_epn_peers_EAMV7107_service_proto_rawDesc), len(file_community_apps_gramx_fifty_zero_epn_epn_peers_EAMV7107_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_community_apps_gramx_fifty_zero_epn_epn_peers_EAMV7107_service_proto_goTypes,
		DependencyIndexes: file_community_apps_gramx_fifty_zero_epn_epn_peers_EAMV7107_service_proto_depIdxs,
	}.Build()
	File_community_apps_gramx_fifty_zero_epn_epn_peers_EAMV7107_service_proto = out.File
	file_community_apps_gramx_fifty_zero_epn_epn_peers_EAMV7107_service_proto_goTypes = nil
	file_community_apps_gramx_fifty_zero_epn_epn_peers_EAMV7107_service_proto_depIdxs = nil
}
