// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: community/apps/gramx/fifty/zero/epn/epn_peers/EAMV7101_service.proto

package services

import (
	context "context"
	entities "github.com/50gramx/eapp-golang-domain/community/apps/gramx/fifty/zero/epn/epn_peers/entities"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EAMV7101DiscoverService_EAMC7101_FullMethodName = "/community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7101DiscoverService/EAMC7101"
)

// EAMV7101DiscoverServiceClient is the client API for EAMV7101DiscoverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EAMV7101DiscoverServiceClient interface {
	EAMC7101(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[entities.EAMV7100, entities.EAMV7101], error)
}

type eAMV7101DiscoverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEAMV7101DiscoverServiceClient(cc grpc.ClientConnInterface) EAMV7101DiscoverServiceClient {
	return &eAMV7101DiscoverServiceClient{cc}
}

func (c *eAMV7101DiscoverServiceClient) EAMC7101(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[entities.EAMV7100, entities.EAMV7101], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EAMV7101DiscoverService_ServiceDesc.Streams[0], EAMV7101DiscoverService_EAMC7101_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[entities.EAMV7100, entities.EAMV7101]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EAMV7101DiscoverService_EAMC7101Client = grpc.ClientStreamingClient[entities.EAMV7100, entities.EAMV7101]

// EAMV7101DiscoverServiceServer is the server API for EAMV7101DiscoverService service.
// All implementations must embed UnimplementedEAMV7101DiscoverServiceServer
// for forward compatibility.
type EAMV7101DiscoverServiceServer interface {
	EAMC7101(grpc.ClientStreamingServer[entities.EAMV7100, entities.EAMV7101]) error
	mustEmbedUnimplementedEAMV7101DiscoverServiceServer()
}

// UnimplementedEAMV7101DiscoverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEAMV7101DiscoverServiceServer struct{}

func (UnimplementedEAMV7101DiscoverServiceServer) EAMC7101(grpc.ClientStreamingServer[entities.EAMV7100, entities.EAMV7101]) error {
	return status.Errorf(codes.Unimplemented, "method EAMC7101 not implemented")
}
func (UnimplementedEAMV7101DiscoverServiceServer) mustEmbedUnimplementedEAMV7101DiscoverServiceServer() {
}
func (UnimplementedEAMV7101DiscoverServiceServer) testEmbeddedByValue() {}

// UnsafeEAMV7101DiscoverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EAMV7101DiscoverServiceServer will
// result in compilation errors.
type UnsafeEAMV7101DiscoverServiceServer interface {
	mustEmbedUnimplementedEAMV7101DiscoverServiceServer()
}

func RegisterEAMV7101DiscoverServiceServer(s grpc.ServiceRegistrar, srv EAMV7101DiscoverServiceServer) {
	// If the following call pancis, it indicates UnimplementedEAMV7101DiscoverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EAMV7101DiscoverService_ServiceDesc, srv)
}

func _EAMV7101DiscoverService_EAMC7101_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EAMV7101DiscoverServiceServer).EAMC7101(&grpc.GenericServerStream[entities.EAMV7100, entities.EAMV7101]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EAMV7101DiscoverService_EAMC7101Server = grpc.ClientStreamingServer[entities.EAMV7100, entities.EAMV7101]

// EAMV7101DiscoverService_ServiceDesc is the grpc.ServiceDesc for EAMV7101DiscoverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EAMV7101DiscoverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7101DiscoverService",
	HandlerType: (*EAMV7101DiscoverServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EAMC7101",
			Handler:       _EAMV7101DiscoverService_EAMC7101_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "community/apps/gramx/fifty/zero/epn/epn_peers/EAMV7101_service.proto",
}
