// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: community/apps/gramx/fifty/zero/epn/epn_peers/EAMV7103_service.proto

package services

import (
	context "context"
	entities "github.com/50gramx/eapp-golang-domain/community/apps/gramx/fifty/zero/epn/epn_peers/entities"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EAMV7103DiscoverService_EAMC7102_FullMethodName = "/community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7103DiscoverService/EAMC7102"
)

// EAMV7103DiscoverServiceClient is the client API for EAMV7103DiscoverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EAMV7103DiscoverServiceClient interface {
	EAMC7102(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[entities.EAMV7100, entities.EAMV7103], error)
}

type eAMV7103DiscoverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEAMV7103DiscoverServiceClient(cc grpc.ClientConnInterface) EAMV7103DiscoverServiceClient {
	return &eAMV7103DiscoverServiceClient{cc}
}

func (c *eAMV7103DiscoverServiceClient) EAMC7102(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[entities.EAMV7100, entities.EAMV7103], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EAMV7103DiscoverService_ServiceDesc.Streams[0], EAMV7103DiscoverService_EAMC7102_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[entities.EAMV7100, entities.EAMV7103]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EAMV7103DiscoverService_EAMC7102Client = grpc.ClientStreamingClient[entities.EAMV7100, entities.EAMV7103]

// EAMV7103DiscoverServiceServer is the server API for EAMV7103DiscoverService service.
// All implementations must embed UnimplementedEAMV7103DiscoverServiceServer
// for forward compatibility.
type EAMV7103DiscoverServiceServer interface {
	EAMC7102(grpc.ClientStreamingServer[entities.EAMV7100, entities.EAMV7103]) error
	mustEmbedUnimplementedEAMV7103DiscoverServiceServer()
}

// UnimplementedEAMV7103DiscoverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEAMV7103DiscoverServiceServer struct{}

func (UnimplementedEAMV7103DiscoverServiceServer) EAMC7102(grpc.ClientStreamingServer[entities.EAMV7100, entities.EAMV7103]) error {
	return status.Errorf(codes.Unimplemented, "method EAMC7102 not implemented")
}
func (UnimplementedEAMV7103DiscoverServiceServer) mustEmbedUnimplementedEAMV7103DiscoverServiceServer() {
}
func (UnimplementedEAMV7103DiscoverServiceServer) testEmbeddedByValue() {}

// UnsafeEAMV7103DiscoverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EAMV7103DiscoverServiceServer will
// result in compilation errors.
type UnsafeEAMV7103DiscoverServiceServer interface {
	mustEmbedUnimplementedEAMV7103DiscoverServiceServer()
}

func RegisterEAMV7103DiscoverServiceServer(s grpc.ServiceRegistrar, srv EAMV7103DiscoverServiceServer) {
	// If the following call pancis, it indicates UnimplementedEAMV7103DiscoverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EAMV7103DiscoverService_ServiceDesc, srv)
}

func _EAMV7103DiscoverService_EAMC7102_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EAMV7103DiscoverServiceServer).EAMC7102(&grpc.GenericServerStream[entities.EAMV7100, entities.EAMV7103]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EAMV7103DiscoverService_EAMC7102Server = grpc.ClientStreamingServer[entities.EAMV7100, entities.EAMV7103]

// EAMV7103DiscoverService_ServiceDesc is the grpc.ServiceDesc for EAMV7103DiscoverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EAMV7103DiscoverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7103DiscoverService",
	HandlerType: (*EAMV7103DiscoverServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EAMC7102",
			Handler:       _EAMV7103DiscoverService_EAMC7102_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "community/apps/gramx/fifty/zero/epn/epn_peers/EAMV7103_service.proto",
}
