// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: community/apps/gramx/fifty/zero/epn/epn_peers/EAMV7107_service.proto

package services

import (
	context "context"
	entities "github.com/50gramx/eapp-golang-domain/community/apps/gramx/fifty/zero/epn/epn_peers/entities"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EAMV7107DiscoverService_EAMC7104_FullMethodName = "/community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7107DiscoverService/EAMC7104"
)

// EAMV7107DiscoverServiceClient is the client API for EAMV7107DiscoverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EAMV7107DiscoverServiceClient interface {
	EAMC7104(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[entities.EAMV7106, entities.EAMV7107], error)
}

type eAMV7107DiscoverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEAMV7107DiscoverServiceClient(cc grpc.ClientConnInterface) EAMV7107DiscoverServiceClient {
	return &eAMV7107DiscoverServiceClient{cc}
}

func (c *eAMV7107DiscoverServiceClient) EAMC7104(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[entities.EAMV7106, entities.EAMV7107], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EAMV7107DiscoverService_ServiceDesc.Streams[0], EAMV7107DiscoverService_EAMC7104_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[entities.EAMV7106, entities.EAMV7107]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EAMV7107DiscoverService_EAMC7104Client = grpc.ClientStreamingClient[entities.EAMV7106, entities.EAMV7107]

// EAMV7107DiscoverServiceServer is the server API for EAMV7107DiscoverService service.
// All implementations must embed UnimplementedEAMV7107DiscoverServiceServer
// for forward compatibility.
type EAMV7107DiscoverServiceServer interface {
	EAMC7104(grpc.ClientStreamingServer[entities.EAMV7106, entities.EAMV7107]) error
	mustEmbedUnimplementedEAMV7107DiscoverServiceServer()
}

// UnimplementedEAMV7107DiscoverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEAMV7107DiscoverServiceServer struct{}

func (UnimplementedEAMV7107DiscoverServiceServer) EAMC7104(grpc.ClientStreamingServer[entities.EAMV7106, entities.EAMV7107]) error {
	return status.Errorf(codes.Unimplemented, "method EAMC7104 not implemented")
}
func (UnimplementedEAMV7107DiscoverServiceServer) mustEmbedUnimplementedEAMV7107DiscoverServiceServer() {
}
func (UnimplementedEAMV7107DiscoverServiceServer) testEmbeddedByValue() {}

// UnsafeEAMV7107DiscoverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EAMV7107DiscoverServiceServer will
// result in compilation errors.
type UnsafeEAMV7107DiscoverServiceServer interface {
	mustEmbedUnimplementedEAMV7107DiscoverServiceServer()
}

func RegisterEAMV7107DiscoverServiceServer(s grpc.ServiceRegistrar, srv EAMV7107DiscoverServiceServer) {
	// If the following call pancis, it indicates UnimplementedEAMV7107DiscoverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EAMV7107DiscoverService_ServiceDesc, srv)
}

func _EAMV7107DiscoverService_EAMC7104_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EAMV7107DiscoverServiceServer).EAMC7104(&grpc.GenericServerStream[entities.EAMV7106, entities.EAMV7107]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EAMV7107DiscoverService_EAMC7104Server = grpc.ClientStreamingServer[entities.EAMV7106, entities.EAMV7107]

// EAMV7107DiscoverService_ServiceDesc is the grpc.ServiceDesc for EAMV7107DiscoverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EAMV7107DiscoverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7107DiscoverService",
	HandlerType: (*EAMV7107DiscoverServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EAMC7104",
			Handler:       _EAMV7107DiscoverService_EAMC7104_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "community/apps/gramx/fifty/zero/epn/epn_peers/EAMV7107_service.proto",
}
