// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: community/apps/gramx/fifty/zero/epn/epn_peers/EAMV7105_service.proto

package services

import (
	context "context"
	entities "github.com/50gramx/eapp-golang-domain/community/apps/gramx/fifty/zero/epn/epn_peers/entities"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EAMV7105DiscoverService_EAMC7103_FullMethodName = "/community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7105DiscoverService/EAMC7103"
)

// EAMV7105DiscoverServiceClient is the client API for EAMV7105DiscoverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EAMV7105DiscoverServiceClient interface {
	EAMC7103(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[entities.EAMV7104, entities.EAMV7105], error)
}

type eAMV7105DiscoverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEAMV7105DiscoverServiceClient(cc grpc.ClientConnInterface) EAMV7105DiscoverServiceClient {
	return &eAMV7105DiscoverServiceClient{cc}
}

func (c *eAMV7105DiscoverServiceClient) EAMC7103(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[entities.EAMV7104, entities.EAMV7105], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EAMV7105DiscoverService_ServiceDesc.Streams[0], EAMV7105DiscoverService_EAMC7103_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[entities.EAMV7104, entities.EAMV7105]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EAMV7105DiscoverService_EAMC7103Client = grpc.ClientStreamingClient[entities.EAMV7104, entities.EAMV7105]

// EAMV7105DiscoverServiceServer is the server API for EAMV7105DiscoverService service.
// All implementations must embed UnimplementedEAMV7105DiscoverServiceServer
// for forward compatibility.
type EAMV7105DiscoverServiceServer interface {
	EAMC7103(grpc.ClientStreamingServer[entities.EAMV7104, entities.EAMV7105]) error
	mustEmbedUnimplementedEAMV7105DiscoverServiceServer()
}

// UnimplementedEAMV7105DiscoverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEAMV7105DiscoverServiceServer struct{}

func (UnimplementedEAMV7105DiscoverServiceServer) EAMC7103(grpc.ClientStreamingServer[entities.EAMV7104, entities.EAMV7105]) error {
	return status.Errorf(codes.Unimplemented, "method EAMC7103 not implemented")
}
func (UnimplementedEAMV7105DiscoverServiceServer) mustEmbedUnimplementedEAMV7105DiscoverServiceServer() {
}
func (UnimplementedEAMV7105DiscoverServiceServer) testEmbeddedByValue() {}

// UnsafeEAMV7105DiscoverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EAMV7105DiscoverServiceServer will
// result in compilation errors.
type UnsafeEAMV7105DiscoverServiceServer interface {
	mustEmbedUnimplementedEAMV7105DiscoverServiceServer()
}

func RegisterEAMV7105DiscoverServiceServer(s grpc.ServiceRegistrar, srv EAMV7105DiscoverServiceServer) {
	// If the following call pancis, it indicates UnimplementedEAMV7105DiscoverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EAMV7105DiscoverService_ServiceDesc, srv)
}

func _EAMV7105DiscoverService_EAMC7103_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EAMV7105DiscoverServiceServer).EAMC7103(&grpc.GenericServerStream[entities.EAMV7104, entities.EAMV7105]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EAMV7105DiscoverService_EAMC7103Server = grpc.ClientStreamingServer[entities.EAMV7104, entities.EAMV7105]

// EAMV7105DiscoverService_ServiceDesc is the grpc.ServiceDesc for EAMV7105DiscoverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EAMV7105DiscoverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7105DiscoverService",
	HandlerType: (*EAMV7105DiscoverServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EAMC7103",
			Handler:       _EAMV7105DiscoverService_EAMC7103_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "community/apps/gramx/fifty/zero/epn/epn_peers/EAMV7105_service.proto",
}
