// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: community/apps/gramx/fifty/zero/epn/epn_agent_chat/EAMV6002_service.proto

package services

import (
	entities "github.com/50gramx/eapp-golang-domain/community/apps/gramx/fifty/zero/epn/epn_agent_chat/entities"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_community_apps_gramx_fifty_zero_epn_epn_agent_chat_EAMV6002_service_proto protoreflect.FileDescriptor

const file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_EAMV6002_service_proto_rawDesc = "" +
	"\n" +
	"Icommunity/apps/gramx/fifty/zero/epn/epn_agent_chat/EAMV6002_service.proto\x122community.apps.gramx.fifty.zero.epn.epn_agent_chat\x1aAcommunity/apps/gramx/fifty/zero/epn/epn_agent_chat/entities.proto2\xa2\x01\n" +
	"\x17EAMV6002DiscoverService\x12\x86\x01\n" +
	"\bEAMC6002\x12<.community.apps.gramx.fifty.zero.epn.epn_agent_chat.EAMV6001\x1a<.community.apps.gramx.fifty.zero.epn.epn_agent_chat.EAMV6002BlZjgithub.com/50gramx/eapp-golang-domain/community/apps/gramx/fifty/zero/epn/epn_agent_chat/services;servicesb\x06proto3"

var file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_EAMV6002_service_proto_goTypes = []any{
	(*entities.EAMV6001)(nil), // 0: community.apps.gramx.fifty.zero.epn.epn_agent_chat.EAMV6001
	(*entities.EAMV6002)(nil), // 1: community.apps.gramx.fifty.zero.epn.epn_agent_chat.EAMV6002
}
var file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_EAMV6002_service_proto_depIdxs = []int32{
	0, // 0: community.apps.gramx.fifty.zero.epn.epn_agent_chat.EAMV6002DiscoverService.EAMC6002:input_type -> community.apps.gramx.fifty.zero.epn.epn_agent_chat.EAMV6001
	1, // 1: community.apps.gramx.fifty.zero.epn.epn_agent_chat.EAMV6002DiscoverService.EAMC6002:output_type -> community.apps.gramx.fifty.zero.epn.epn_agent_chat.EAMV6002
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_EAMV6002_service_proto_init() }
func file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_EAMV6002_service_proto_init() {
	if File_community_apps_gramx_fifty_zero_epn_epn_agent_chat_EAMV6002_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_EAMV6002_service_proto_rawDesc), len(file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_EAMV6002_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_EAMV6002_service_proto_goTypes,
		DependencyIndexes: file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_EAMV6002_service_proto_depIdxs,
	}.Build()
	File_community_apps_gramx_fifty_zero_epn_epn_agent_chat_EAMV6002_service_proto = out.File
	file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_EAMV6002_service_proto_goTypes = nil
	file_community_apps_gramx_fifty_zero_epn_epn_agent_chat_EAMV6002_service_proto_depIdxs = nil
}
