// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: community/apps/gramx/fifty/zero/epn/epn_agent_chat/EAMV6002_service.proto

package services

import (
	context "context"
	entities "github.com/50gramx/eapp-golang-domain/community/apps/gramx/fifty/zero/epn/epn_agent_chat/entities"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EAMV6002DiscoverService_EAMC6002_FullMethodName = "/community.apps.gramx.fifty.zero.epn.epn_agent_chat.EAMV6002DiscoverService/EAMC6002"
)

// EAMV6002DiscoverServiceClient is the client API for EAMV6002DiscoverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EAMV6002DiscoverServiceClient interface {
	EAMC6002(ctx context.Context, in *entities.EAMV6001, opts ...grpc.CallOption) (grpc.ServerStreamingClient[entities.EAMV6002], error)
}

type eAMV6002DiscoverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEAMV6002DiscoverServiceClient(cc grpc.ClientConnInterface) EAMV6002DiscoverServiceClient {
	return &eAMV6002DiscoverServiceClient{cc}
}

func (c *eAMV6002DiscoverServiceClient) EAMC6002(ctx context.Context, in *entities.EAMV6001, opts ...grpc.CallOption) (grpc.ServerStreamingClient[entities.EAMV6002], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EAMV6002DiscoverService_ServiceDesc.Streams[0], EAMV6002DiscoverService_EAMC6002_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[entities.EAMV6001, entities.EAMV6002]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EAMV6002DiscoverService_EAMC6002Client = grpc.ServerStreamingClient[entities.EAMV6002]

// EAMV6002DiscoverServiceServer is the server API for EAMV6002DiscoverService service.
// All implementations must embed UnimplementedEAMV6002DiscoverServiceServer
// for forward compatibility.
type EAMV6002DiscoverServiceServer interface {
	EAMC6002(*entities.EAMV6001, grpc.ServerStreamingServer[entities.EAMV6002]) error
	mustEmbedUnimplementedEAMV6002DiscoverServiceServer()
}

// UnimplementedEAMV6002DiscoverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEAMV6002DiscoverServiceServer struct{}

func (UnimplementedEAMV6002DiscoverServiceServer) EAMC6002(*entities.EAMV6001, grpc.ServerStreamingServer[entities.EAMV6002]) error {
	return status.Errorf(codes.Unimplemented, "method EAMC6002 not implemented")
}
func (UnimplementedEAMV6002DiscoverServiceServer) mustEmbedUnimplementedEAMV6002DiscoverServiceServer() {
}
func (UnimplementedEAMV6002DiscoverServiceServer) testEmbeddedByValue() {}

// UnsafeEAMV6002DiscoverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EAMV6002DiscoverServiceServer will
// result in compilation errors.
type UnsafeEAMV6002DiscoverServiceServer interface {
	mustEmbedUnimplementedEAMV6002DiscoverServiceServer()
}

func RegisterEAMV6002DiscoverServiceServer(s grpc.ServiceRegistrar, srv EAMV6002DiscoverServiceServer) {
	// If the following call pancis, it indicates UnimplementedEAMV6002DiscoverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EAMV6002DiscoverService_ServiceDesc, srv)
}

func _EAMV6002DiscoverService_EAMC6002_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(entities.EAMV6001)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EAMV6002DiscoverServiceServer).EAMC6002(m, &grpc.GenericServerStream[entities.EAMV6001, entities.EAMV6002]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EAMV6002DiscoverService_EAMC6002Server = grpc.ServerStreamingServer[entities.EAMV6002]

// EAMV6002DiscoverService_ServiceDesc is the grpc.ServiceDesc for EAMV6002DiscoverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EAMV6002DiscoverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "community.apps.gramx.fifty.zero.epn.epn_agent_chat.EAMV6002DiscoverService",
	HandlerType: (*EAMV6002DiscoverServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EAMC6002",
			Handler:       _EAMV6002DiscoverService_EAMC6002_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "community/apps/gramx/fifty/zero/epn/epn_agent_chat/EAMV6002_service.proto",
}
