// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: community/apps/gramx/fifty/zero/ethos/mesh_demo/EAMV8001_service.proto

package services

import (
	context "context"
	entities "github.com/50gramx/eapp-golang-domain/community/apps/gramx/fifty/zero/ethos/mesh_demo/entities"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EAMV8001DiscoverService_EAMC8001_FullMethodName = "/community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001DiscoverService/EAMC8001"
	EAMV8001DiscoverService_EAMC8002_FullMethodName = "/community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001DiscoverService/EAMC8002"
	EAMV8001DiscoverService_EAMC8003_FullMethodName = "/community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001DiscoverService/EAMC8003"
	EAMV8001DiscoverService_EAMC8004_FullMethodName = "/community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001DiscoverService/EAMC8004"
)

// EAMV8001DiscoverServiceClient is the client API for EAMV8001DiscoverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EAMV8001DiscoverServiceClient interface {
	EAMC8001(ctx context.Context, in *entities.EAMV8002, opts ...grpc.CallOption) (*entities.EAMV8001, error)
	EAMC8002(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[entities.EAMV8002, entities.EAMV8001], error)
	EAMC8003(ctx context.Context, in *entities.EAMV8002, opts ...grpc.CallOption) (grpc.ServerStreamingClient[entities.EAMV8001], error)
	EAMC8004(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[entities.EAMV8002, entities.EAMV8001], error)
}

type eAMV8001DiscoverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEAMV8001DiscoverServiceClient(cc grpc.ClientConnInterface) EAMV8001DiscoverServiceClient {
	return &eAMV8001DiscoverServiceClient{cc}
}

func (c *eAMV8001DiscoverServiceClient) EAMC8001(ctx context.Context, in *entities.EAMV8002, opts ...grpc.CallOption) (*entities.EAMV8001, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(entities.EAMV8001)
	err := c.cc.Invoke(ctx, EAMV8001DiscoverService_EAMC8001_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eAMV8001DiscoverServiceClient) EAMC8002(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[entities.EAMV8002, entities.EAMV8001], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EAMV8001DiscoverService_ServiceDesc.Streams[0], EAMV8001DiscoverService_EAMC8002_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[entities.EAMV8002, entities.EAMV8001]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EAMV8001DiscoverService_EAMC8002Client = grpc.ClientStreamingClient[entities.EAMV8002, entities.EAMV8001]

func (c *eAMV8001DiscoverServiceClient) EAMC8003(ctx context.Context, in *entities.EAMV8002, opts ...grpc.CallOption) (grpc.ServerStreamingClient[entities.EAMV8001], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EAMV8001DiscoverService_ServiceDesc.Streams[1], EAMV8001DiscoverService_EAMC8003_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[entities.EAMV8002, entities.EAMV8001]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EAMV8001DiscoverService_EAMC8003Client = grpc.ServerStreamingClient[entities.EAMV8001]

func (c *eAMV8001DiscoverServiceClient) EAMC8004(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[entities.EAMV8002, entities.EAMV8001], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EAMV8001DiscoverService_ServiceDesc.Streams[2], EAMV8001DiscoverService_EAMC8004_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[entities.EAMV8002, entities.EAMV8001]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EAMV8001DiscoverService_EAMC8004Client = grpc.BidiStreamingClient[entities.EAMV8002, entities.EAMV8001]

// EAMV8001DiscoverServiceServer is the server API for EAMV8001DiscoverService service.
// All implementations must embed UnimplementedEAMV8001DiscoverServiceServer
// for forward compatibility.
type EAMV8001DiscoverServiceServer interface {
	EAMC8001(context.Context, *entities.EAMV8002) (*entities.EAMV8001, error)
	EAMC8002(grpc.ClientStreamingServer[entities.EAMV8002, entities.EAMV8001]) error
	EAMC8003(*entities.EAMV8002, grpc.ServerStreamingServer[entities.EAMV8001]) error
	EAMC8004(grpc.BidiStreamingServer[entities.EAMV8002, entities.EAMV8001]) error
	mustEmbedUnimplementedEAMV8001DiscoverServiceServer()
}

// UnimplementedEAMV8001DiscoverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEAMV8001DiscoverServiceServer struct{}

func (UnimplementedEAMV8001DiscoverServiceServer) EAMC8001(context.Context, *entities.EAMV8002) (*entities.EAMV8001, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EAMC8001 not implemented")
}
func (UnimplementedEAMV8001DiscoverServiceServer) EAMC8002(grpc.ClientStreamingServer[entities.EAMV8002, entities.EAMV8001]) error {
	return status.Errorf(codes.Unimplemented, "method EAMC8002 not implemented")
}
func (UnimplementedEAMV8001DiscoverServiceServer) EAMC8003(*entities.EAMV8002, grpc.ServerStreamingServer[entities.EAMV8001]) error {
	return status.Errorf(codes.Unimplemented, "method EAMC8003 not implemented")
}
func (UnimplementedEAMV8001DiscoverServiceServer) EAMC8004(grpc.BidiStreamingServer[entities.EAMV8002, entities.EAMV8001]) error {
	return status.Errorf(codes.Unimplemented, "method EAMC8004 not implemented")
}
func (UnimplementedEAMV8001DiscoverServiceServer) mustEmbedUnimplementedEAMV8001DiscoverServiceServer() {
}
func (UnimplementedEAMV8001DiscoverServiceServer) testEmbeddedByValue() {}

// UnsafeEAMV8001DiscoverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EAMV8001DiscoverServiceServer will
// result in compilation errors.
type UnsafeEAMV8001DiscoverServiceServer interface {
	mustEmbedUnimplementedEAMV8001DiscoverServiceServer()
}

func RegisterEAMV8001DiscoverServiceServer(s grpc.ServiceRegistrar, srv EAMV8001DiscoverServiceServer) {
	// If the following call pancis, it indicates UnimplementedEAMV8001DiscoverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EAMV8001DiscoverService_ServiceDesc, srv)
}

func _EAMV8001DiscoverService_EAMC8001_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(entities.EAMV8002)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EAMV8001DiscoverServiceServer).EAMC8001(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EAMV8001DiscoverService_EAMC8001_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EAMV8001DiscoverServiceServer).EAMC8001(ctx, req.(*entities.EAMV8002))
	}
	return interceptor(ctx, in, info, handler)
}

func _EAMV8001DiscoverService_EAMC8002_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EAMV8001DiscoverServiceServer).EAMC8002(&grpc.GenericServerStream[entities.EAMV8002, entities.EAMV8001]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EAMV8001DiscoverService_EAMC8002Server = grpc.ClientStreamingServer[entities.EAMV8002, entities.EAMV8001]

func _EAMV8001DiscoverService_EAMC8003_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(entities.EAMV8002)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EAMV8001DiscoverServiceServer).EAMC8003(m, &grpc.GenericServerStream[entities.EAMV8002, entities.EAMV8001]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EAMV8001DiscoverService_EAMC8003Server = grpc.ServerStreamingServer[entities.EAMV8001]

func _EAMV8001DiscoverService_EAMC8004_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EAMV8001DiscoverServiceServer).EAMC8004(&grpc.GenericServerStream[entities.EAMV8002, entities.EAMV8001]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EAMV8001DiscoverService_EAMC8004Server = grpc.BidiStreamingServer[entities.EAMV8002, entities.EAMV8001]

// EAMV8001DiscoverService_ServiceDesc is the grpc.ServiceDesc for EAMV8001DiscoverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EAMV8001DiscoverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001DiscoverService",
	HandlerType: (*EAMV8001DiscoverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EAMC8001",
			Handler:    _EAMV8001DiscoverService_EAMC8001_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EAMC8002",
			Handler:       _EAMV8001DiscoverService_EAMC8002_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "EAMC8003",
			Handler:       _EAMV8001DiscoverService_EAMC8003_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "EAMC8004",
			Handler:       _EAMV8001DiscoverService_EAMC8004_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "community/apps/gramx/fifty/zero/ethos/mesh_demo/EAMV8001_service.proto",
}
