// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: community/apps/gramx/fifty/zero/ethos/mesh_demo/EAMV8001_service.proto

package services

import (
	entities "github.com/50gramx/eapp-golang-domain/community/apps/gramx/fifty/zero/ethos/mesh_demo/entities"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_community_apps_gramx_fifty_zero_ethos_mesh_demo_EAMV8001_service_proto protoreflect.FileDescriptor

const file_community_apps_gramx_fifty_zero_ethos_mesh_demo_EAMV8001_service_proto_rawDesc = "" +
	"\n" +
	"Fcommunity/apps/gramx/fifty/zero/ethos/mesh_demo/EAMV8001_service.proto\x12/community.apps.gramx.fifty.zero.ethos.mesh_demo\x1a>community/apps/gramx/fifty/zero/ethos/mesh_demo/entities.proto2\xad\x04\n" +
	"\x17EAMV8001DiscoverService\x12\x80\x01\n" +
	"\bEAMC8001\x129.community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8002\x1a9.community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001\x12\x82\x01\n" +
	"\bEAMC8002\x129.community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8002\x1a9.community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001(\x01\x12\x82\x01\n" +
	"\bEAMC8003\x129.community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8002\x1a9.community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV80010\x01\x12\x84\x01\n" +
	"\bEAMC8004\x129.community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8002\x1a9.community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001(\x010\x01BiZggithub.com/50gramx/eapp-golang-domain/community/apps/gramx/fifty/zero/ethos/mesh_demo/services;servicesb\x06proto3"

var file_community_apps_gramx_fifty_zero_ethos_mesh_demo_EAMV8001_service_proto_goTypes = []any{
	(*entities.EAMV8002)(nil), // 0: community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8002
	(*entities.EAMV8001)(nil), // 1: community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001
}
var file_community_apps_gramx_fifty_zero_ethos_mesh_demo_EAMV8001_service_proto_depIdxs = []int32{
	0, // 0: community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001DiscoverService.EAMC8001:input_type -> community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8002
	0, // 1: community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001DiscoverService.EAMC8002:input_type -> community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8002
	0, // 2: community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001DiscoverService.EAMC8003:input_type -> community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8002
	0, // 3: community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001DiscoverService.EAMC8004:input_type -> community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8002
	1, // 4: community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001DiscoverService.EAMC8001:output_type -> community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001
	1, // 5: community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001DiscoverService.EAMC8002:output_type -> community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001
	1, // 6: community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001DiscoverService.EAMC8003:output_type -> community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001
	1, // 7: community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001DiscoverService.EAMC8004:output_type -> community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8001
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_community_apps_gramx_fifty_zero_ethos_mesh_demo_EAMV8001_service_proto_init() }
func file_community_apps_gramx_fifty_zero_ethos_mesh_demo_EAMV8001_service_proto_init() {
	if File_community_apps_gramx_fifty_zero_ethos_mesh_demo_EAMV8001_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_community_apps_gramx_fifty_zero_ethos_mesh_demo_EAMV8001_service_proto_rawDesc), len(file_community_apps_gramx_fifty_zero_ethos_mesh_demo_EAMV8001_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_community_apps_gramx_fifty_zero_ethos_mesh_demo_EAMV8001_service_proto_goTypes,
		DependencyIndexes: file_community_apps_gramx_fifty_zero_ethos_mesh_demo_EAMV8001_service_proto_depIdxs,
	}.Build()
	File_community_apps_gramx_fifty_zero_ethos_mesh_demo_EAMV8001_service_proto = out.File
	file_community_apps_gramx_fifty_zero_ethos_mesh_demo_EAMV8001_service_proto_goTypes = nil
	file_community_apps_gramx_fifty_zero_ethos_mesh_demo_EAMV8001_service_proto_depIdxs = nil
}
