// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: community/apps/gramx/fifty/zero/ethos/mesh_demo/EAMV8004_service.proto

package services

import (
	context "context"
	entities "github.com/50gramx/eapp-golang-domain/community/apps/gramx/fifty/zero/ethos/mesh_demo/entities"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EAMV8004DiscoverService_EAMC8005_FullMethodName = "/community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8004DiscoverService/EAMC8005"
)

// EAMV8004DiscoverServiceClient is the client API for EAMV8004DiscoverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EAMV8004DiscoverServiceClient interface {
	EAMC8005(ctx context.Context, in *entities.EAMV8004, opts ...grpc.CallOption) (*entities.EAMV8004, error)
}

type eAMV8004DiscoverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEAMV8004DiscoverServiceClient(cc grpc.ClientConnInterface) EAMV8004DiscoverServiceClient {
	return &eAMV8004DiscoverServiceClient{cc}
}

func (c *eAMV8004DiscoverServiceClient) EAMC8005(ctx context.Context, in *entities.EAMV8004, opts ...grpc.CallOption) (*entities.EAMV8004, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(entities.EAMV8004)
	err := c.cc.Invoke(ctx, EAMV8004DiscoverService_EAMC8005_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EAMV8004DiscoverServiceServer is the server API for EAMV8004DiscoverService service.
// All implementations must embed UnimplementedEAMV8004DiscoverServiceServer
// for forward compatibility.
type EAMV8004DiscoverServiceServer interface {
	EAMC8005(context.Context, *entities.EAMV8004) (*entities.EAMV8004, error)
	mustEmbedUnimplementedEAMV8004DiscoverServiceServer()
}

// UnimplementedEAMV8004DiscoverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEAMV8004DiscoverServiceServer struct{}

func (UnimplementedEAMV8004DiscoverServiceServer) EAMC8005(context.Context, *entities.EAMV8004) (*entities.EAMV8004, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EAMC8005 not implemented")
}
func (UnimplementedEAMV8004DiscoverServiceServer) mustEmbedUnimplementedEAMV8004DiscoverServiceServer() {
}
func (UnimplementedEAMV8004DiscoverServiceServer) testEmbeddedByValue() {}

// UnsafeEAMV8004DiscoverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EAMV8004DiscoverServiceServer will
// result in compilation errors.
type UnsafeEAMV8004DiscoverServiceServer interface {
	mustEmbedUnimplementedEAMV8004DiscoverServiceServer()
}

func RegisterEAMV8004DiscoverServiceServer(s grpc.ServiceRegistrar, srv EAMV8004DiscoverServiceServer) {
	// If the following call pancis, it indicates UnimplementedEAMV8004DiscoverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EAMV8004DiscoverService_ServiceDesc, srv)
}

func _EAMV8004DiscoverService_EAMC8005_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(entities.EAMV8004)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EAMV8004DiscoverServiceServer).EAMC8005(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EAMV8004DiscoverService_EAMC8005_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EAMV8004DiscoverServiceServer).EAMC8005(ctx, req.(*entities.EAMV8004))
	}
	return interceptor(ctx, in, info, handler)
}

// EAMV8004DiscoverService_ServiceDesc is the grpc.ServiceDesc for EAMV8004DiscoverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EAMV8004DiscoverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "community.apps.gramx.fifty.zero.ethos.mesh_demo.EAMV8004DiscoverService",
	HandlerType: (*EAMV8004DiscoverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EAMC8005",
			Handler:    _EAMV8004DiscoverService_EAMC8005_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "community/apps/gramx/fifty/zero/ethos/mesh_demo/EAMV8004_service.proto",
}
